
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "app1"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "app1"

  config.vm.synced_folder ".", "/home/vagrant/code",
    owner: "www-data", group: "www-data"
  
#  config.vm.network "forwarded_port", guest: 80, host: 8000
#  config.vm.network "forwarded_port", guest: 3306, host: 33060
  config.vm.network "public_network", ip: "192.168.0.31", bridge: "wlo1"  
  config.vm.provision "shell", path: "provision.sh"
end
